### ISSUE TITLE
Qu'est ce que la réalité virtuelle ?

### ISSUE THREAD

**Issue by dlevac-crme** [cr-crme/vr_in_rehab#11]
Remove the current text and replace with

La réalité virtuelle se définit comme étant toute technologie permettant une simulation interactive et en temps réel de la réalité, par la création par ordinateur, à l'aide d'images de synthèse, d'un environnement virtuel en 3D dans lequel on peut évoluer (Office québécois de la langue française, 2016).

**Comment by pariterre** [comment]
Done
