### ISSUE TITLE
immersive RV vs non-immersive RV

### ISSUE THREAD

**Issue by dlevac-crme** [cr-crme/vr_in_rehab#12]
Change the title to

La réalité virtuelle immersive vs non-immersive

Remove the current text and change to 

La réalité virtuelle (RV) immersive s’agit des visiocasques qui offrent une expérience tridimensionnelle (3D) où l'affichage visuel change en fonction de l’interaction avec un environnement virtuel. 
Add the picture of the child wearing the visiocasque (either one) in Element.

Dans la réalité virtuelle non immersive, l'environnement virtuel est affiché sur un écran 2D devant l'utilisateur.
(add the picture of the child in front of the TV screen from Element.

**Comment by pariterre** [comment]
Done!
