### ISSUE TITLE
Consoles : texte

### ISSUE THREAD

**Issue by dlevac-crme** [cr-crme/vr_in_rehab#19]
Please bold the categories (ie immersive/non-immersive)

Lorsque le texte s'étend sur plus d'une ligne, commencez-le sous le titre de la catégorie et ajoutez des puces.

ajouter des bullet points pour chaque nouvelle ligne sous les précautions

Il n'est pas nécessaire d'ajouter des bullet points devant les catégories (remove this from all) - les bullet points sont seulement pour chaque ligne d'information sous les catégories.

Place un espace entre chaque catégorie pour mieux répartir le texte (pas d'espace entre les puces d'information dans chaque catégorie).

**Comment by pariterre** [comment]
Done!
