### ISSUE TITLE
au fond du landing page, ajoute ce texte

### ISSUE THREAD

**Issue by dlevac-crme** [cr-crme/vr_in_rehab#5]
Ce site est une initiative d'un projet financé par le FRQS et dirigé par Danielle Levac, chercheuse à la Technopole en réadaptation pédiatrique, Centre de Réadaptation Marie Enfant, CHU Sainte Justine.

Et ajoute les logos du CR-CHUSJ, FRQ-S, le Technopole et LaboInspire (je les mettrai dans element)

**Comment by pariterre** [comment]
Done
